export const existingUsers = [
    
    {
        id: "282b",
        name: "Əliyeva Esmira Namiq qızı",
        pin: "JH87hjhk",
        email: "esmira123@gmail.com",
        code: "stargirl",
        mobile: "12345678",
        otp: true,
        existingUser: true,
        viewed: true,
        operated: false,
        approved: false,
        blocked: false,
        newUser: false,
    },
    {
        id: "2asd82b",
        name: "Muradov Mehman Asif oğlu",
        pin: "HJIByybyy&*",
        email: "mehman123@gmail.com",
        code: "starboy",
        mobile: "12345678",
        otp: true,
        existingUser: true,
        viewed: false,
        operated: true,
        approved: false,
        blocked: true,
        newUser: false,
    },
    {
        id: "2as82asb",
        name: "Məmmədyarov Şəhriyar Abbas oğlu",
        pin: "YTRFlml876",
        email: "shah123@gmail.com",
        code: "starman",
        mobile: "12345678",
        otp: true,
        existingUser: true,
        viewed: false,
        operated: false,
        approved: true,
        blocked: false,
        newUser: false,
    }
  
]