export const newUsers = [
    
        {
          id: "28212eb",
          name: "Əliyeva Leyla Namiq qızı",
          pin: "JH87hjhk",
          email: "esmira123@gmail.com",
          code: "stargirl",
          mobile: "12345678",
          otp: true,
          existingUser: false,
          viewed: false,
          operated: false,
          approved: false,
          blocked: false,
          newUser: true,
        },
        {
          id: "282bhjk",
          name: "Muradov Arif Asif oğlu",
          pin: "JH87hjhk",
          email: "esmira123@gmail.com",
          code: "stargirl",
          mobile: "12345678",
          otp: true,
          existingUser: false,
          viewed: false,
          operated: false,
          approved: false,
          blocked: false,
          newUser: true,
        },
        {
          id: "282bcznskje",
          name: "Məmmədyarov Elmar Abbas oğlu",
          pin: "JH87hjhk",
          email: "esmira123@gmail.com",
          code: "stargirl",
          mobile: "12345678",
          otp: true,
          existingUser: false,
          viewed: false,
          operated: false,
          approved: false,
          blocked: false,
          newUser: true,
        },
      
]